import Head from "next/head";
import Header from "../components/Header";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  return (
    <div>
      <Head>
        <title>Login Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="max-w-7xl mx-auto ">
        <h1 className="text-3xl font-bold underline text-red-500">
          This is the login test:
        </h1>
        <p className="mt-4">
          Currently Logged in by :{" "}
          <span className="font-bold underline text-gray-900">
            {session ? session?.user?.name : "Stranger"}
          </span>
        </p>
        <p>
          Email:{" "}
          <span className="font-bold underline text-gray-900">
            {session ? session?.user?.email : "No user logged in"}
          </span>
        </p>
      </div>
    </div>
  );
}
